# Generated by Django 2.2.6 on 2020-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='botScoreEnglish',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='botScoreUniversal',
            field=models.FloatField(default=-1),
        ),
    ]
