# Generated by Django 2.2.6 on 2020-04-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200426_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='comboned_negative_sentiment',
            new_name='combined_negative_sentiment',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='comboned_neutral_sentiment',
            new_name='combined_neutral_sentiment',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='comboned_overall_sentiment',
            new_name='combined_overall_sentiment',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='comboned_positive_sentiment',
            new_name='combined_positive_sentiment',
        ),
    ]
