# Generated by Django 2.2.6 on 2020-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200426_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='relevancy',
            field=models.FloatField(null=True),
        ),
    ]
