# Generated by Django 2.2.6 on 2020-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tweet_relevancy'),
    ]

    operations = [
        migrations.RunSQL(
            "update myapp_tweet set relevancy=1 where relevancy is null;"
        )
    ]
